server:
  port: 8204
spring:
  application:
    name: service-msm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  sms:
    regionId: default
    accessKeyId: LT6I0Y5633pX89qC
    secret: jX8D04Dm12I3gGKj345FYSzu0fq8mT


